---

defaultMessage: >
  Please consider an alternative to `{{match}}`.

  See https://github.com/ietf/terminology for suggestions.

rules:
  whitelist:
    regex:
      - /\bwhite[ _-]*list\b/gi
    level: failure

  blacklist:
    regex:
      - /\bblack[ _-]*list\b/gi
    level: failure

  master:
    regex:
      - /\bmaster\b/gi
    level: failure

  slave:
    regex:
      - /\bslave\b/gi
    level: failure

  grandfathered:
    regex:
      - /\bgrandfather(ed|ing)\b/gi
    level: failure

  gendered-terms:
    regex:
      - /\bchair[ _-]*man\b/gi
      - /\bmankind\b/gi
      - /\bman[ _-]*month\b/gi
      - /\bmans\b/gi
      - /\bsales[ _-]*man\b/gi
      - /\bman[ _-]*made\b/gi
      - /\bman[ _-]*power\b/gi
      - /\bguys?\b/gi
      - /\blad(y|ies)\b/gi
    level: failure

  gendered-pronouns:
    regex:
      - /\b(he|him|his|she|her|hers)\b/gi
    level: failure

  sanity-check:
    regex:
      - /\bsanity[ _-]*check\b/gi
    level: failure

  crazy:
    regex:
      - /\bcrazy\b/gi
    level: failure

  dummy:
    regex:
      - /\bdummy\b/gi
    level: failure

  dark-pattern:
    regex:
      - /\bdark[ _-]*pattern\b/gi
    level: failure

  balkanization:
    regex:
      - /\bbalkani[zs]\w*\b/gi
    level: failure

ignoreDefaults: true
