---

defaultMessage: >
  Please consider an alternative to `{{match}}`.

  See https://github.com/ietf/terminology for suggestions.

rules:
  whitelist:
    regex:
      - /\bwhite[ _-]*list/gi
    level: failure

  blacklist:
    regex:
      - /\bblack[ _-]*list/gi
    level: failure

  master:
    regex:
      - /\bmaster/gi
    level: failure

  slave:
    regex:
      - /\bslave/gi
    level: failure

  grandfathered:
    regex:
      - /\bgrandfather(s|ed|ing)\b/gi
    level: failure

  gendered-terms:
    regex:
      - /\bchair[ _-]*man/gi
      - /\bmankind\b/gi
      - /\bman[ _-]*month/gi
      - /\bmans\b/gi
      - /\bsales[ _-]*m(a|e)n/gi
      - /\bman[ _-]*made\b/gi
      - /\bman[ _-]*power/gi
      - /\bguys?\b/gi
      - /\blad(y|ie)\'?s?\'?\b/gi
    level: failure

  gendered-pronouns:
    regex:
      - /\b(he|him|his|she|her|hers)\b/gi
    level: failure

  sanity-check:
    regex:
      - /\bsanity[ _-]*check/gi
    level: failure

  crazy:
    regex:
      - /\bcraz(y|ie)/gi
    level: failure

  dummy:
    regex:
      - /\bdummy/gi
    level: failure

  dark-pattern:
    regex:
      - /\bdark[ _-]*pattern/gi
    level: failure

  balkanization:
    regex:
      - /\bbalkani[zs]\w*\b/gi
    level: failure

ignoreDefaults: true
