---

defaultMessage: >
  Please consider an alternative to the term "{{match}}".

  {{#if alternatives~}}
  Possibilities might include: {{#each alternatives}}{{#if @index}},
  {{/if}}"{{this}}"{{/each}}.
  {{~/if}}

  If you believe this warning to be incorrect, please open an issue at
  https://github.com/NTAP/isb-ietf-config/issues.

rules:
  whitelist:
    regex:
      - /\bwhite[\w_-]*list/gi
    level: warning
    alternatives:
      - accept list
      - allowlist
      - approved list
      - pass list
      - permitted

  blacklist:
    regex:
      - /\bblack[\w_-]*list/gi
    level: warning
    alternatives:
      - blocklist
      - denylist
      - prohibited
      - refused
      - reject list
      - unapproved list

  master:
    regex:
      - /\bmaster/gi
    level: warning
    alternatives:
      - active
      - central
      - initiator
      - leader
      - main
      - orchestrator
      - parent
      - primary
      - server

  slave:
    regex:
      - /\bslave/gi
    level: warning
    alternatives:
      - follower
      - peripheral
      - replica
      - responder
      - secondary
      - standby
      - worker

  grandfathered:
    regex:
      - /\bgrandfather/gi
    level: warning
    alternatives:
      - exemption
      - historical
      - legacy status
      - pre-approved
      - special case

  gendered-terms:
    regex:
      - /\bchair[\w_-]*man/gi
      - /\bmankind\b/gi
      - /\bman[\w_-]*month/gi
      - /\bmans\b/gi
      - /\bsales[\w_-]*m(a|e)n/gi
      - /\bman[\w_-]*made\b/gi
      - /\bman[\w_-]*power/gi
      - /\bguys?\b/gi
      - /\blad(y|ie)\'?s?\'?\b/gi
    level: warning
    alternatives:
      - people

  gendered-pronouns:
    regex:
      - /\b(he|him|his|she|her|hers)\b/gi
    level: warning
    alternatives:
      - they
      - them
      - their

  sanity-check:
    regex:
      - /\bsanity[\w_-]*check/gi
    level: warning
    alternatives:
      - coherence check
      - confidence check
      - quick check

  crazy:
    regex:
      - /\bcraz(y|ie)?/gi
    level: warning
    alternatives:
      - malfunctioning
      - puzzling
      - surprising
      - unexpected

  dummy:
    regex:
      - /\bdummy/gi
    level: warning
    alternatives:
      - placeholder
      - sample
      - stand-in
      - substitute

  dark-pattern:
    regex:
      - /\bdark[\w_-]*pattern/gi
    level: warning
    alternatives:
      - deception pattern

  balkanization:
    regex:
      - /\bbalkani[zs]\w*\b/gi
    level: warning
    alternatives:
      - bifurcation
      - segmentation

  blackmail:
    regex:
      - /\bblack[\w_-]*mail/gi
    level: warning
    alternatives:
      - extortion

  black-sheep:
    regex:
      - /\bblack[\w_-]*sheep/gi
    level: warning
    alternatives:
      - disreputable

  black-market:
    regex:
      - /\bblack[\w_-]*market/gi
    level: warning
    alternatives:
      - illegal marketplace

  tradition:
    regex:
      - /\btradition/gi
    level: warning
    alternatives:
      - classic
      - classical
      - common
      - conventional
      - customary
      - fixed
      - habitual
      - historic
      - long-established
      - popular
      - prescribed
      - regular
      - rooted
      - time-honored
      - universal
      - widely used
      - widespread

  native:
    regex:
      - /\bnative/gi
    level: warning
    alternatives:
      - built-in
      - fundamental
      - ingrained
      - intrinsic
      - original

  elder:
    regex:
      - /\belder/gi
    level: warning
    alternatives:
      - aged
      - aging
      - old

  dumb:
    regex:
      - /\bdumb?/gi
    level: warning
    alternatives:
      - dull
      - inarticuate
      - incoherent

  immature:
    regex:
      - /\bimmature/gi
    level: warning
    alternatives:
      - imperfect
      - premature
      - underdeveloped
      - unfinished
      - unsophisticated

  cripple:
    regex:
      - /\bcrippl/gi
    level: warning
    alternatives:
      - broken
      - damaged
      - defective
      - deformed
      - impaired

  handicap:
    regex:
      - /\bhandicap/gi
    level: warning
    alternatives:
      - broken
      - damaged
      - defective
      - deformed
      - impaired

  gendered-connectors:
    regex:
      - /\b(fe)?male[\w_-]*(connector|end)/gi
    level: warning
    alternatives:
      - plug
      - socket

ignoreDefaults: true
